quarkus.log.file.enabled=true
quarkus.log.file.path=logs/application.log

quarkus.hibernate-orm.schema-management.strategy=drop-and-create

%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://prod-host:5432/mydb
%prod.quarkus.datasource.username=${DB_USER}
%prod.quarkus.datasource.password=${DB_PASS}
%prod.quarkus.hibernate-orm.schema-management.strategy=none