/*some initial data to play with - generated by claude based on tests*/

-- Accounts
-- id 1: user 22 — funded, source for a successful transfer, also for self-transfer (400) test
INSERT INTO account (id, heldFunds, ownerid) VALUES (1, 1000, 22);

-- id 2: user 22 — zero balance. Second account for the same owner (demonstrates LIST
-- returning >1 account), and source for the insufficient-funds (409) test
INSERT INTO account (id, heldFunds, ownerid) VALUES (2, 0, 22);

-- id 3: user 42 — different owner. Valid transfer target from account 1, and
-- source for the ownership/403 test when attempted as user 22
INSERT INTO account (id, heldFunds, ownerid) VALUES (3, 2500, 42);

-- Transactions (pre-seeded audit history for account 1 <-> account 3)
INSERT INTO transaction (id, fromid, toid, amount, timestamp) VALUES (1, 1, 3, 200, now() - interval '2 days');
INSERT INTO transaction (id, fromid, toid, amount, timestamp) VALUES (2, 1, 3, 50,  now() - interval '1 day');

-- Bump sequences so app-generated ids don't collide with the hardcoded ones above
SELECT setval('account_seq', (SELECT MAX(id) FROM account));
SELECT setval('transaction_seq', (SELECT MAX(id) FROM transaction));